apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvilops
  namespace: anvilops-dev
  labels:
    app.kubernetes.io/name: anvilops
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/managed-by: fluxcd
spec:
  selector:
    matchLabels:
      app: anvilops
  template:
    metadata:
      labels:
        app: anvilops
    spec:
      containers:
        - name: anvilops
          image: registry.anvil.rcac.purdue.edu/anvilops/anvilops:main-261-a7a8be5ddd59ed72d804c0bea364b7adc8ba6667 # {"$imagepolicy": "anvilops-dev:anvilops-imagepolicy"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 512m
            limits:
              memory: 1Gi
              cpu: 1024m
          env:
            - name: POSTGRES_USER
              value: anvilops
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: POSTGRES_DB
              value: anvilops
            - name: POSTGRES_HOSTNAME
              value: anvilops-postgres
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cilogon-credentials
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cilogon-credentials
                  key: client-secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cilogon-credentials
                  key: session-secret
            - name: CALLBACK_URL
              value: https://anvilops.rcac.purdue.edu/api/oauth_callback
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: webhook-secret
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: app-id
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: private-key
            - name: GITHUB_BASE_URL
              value: https://github.rcac.purdue.edu
            - name: GITHUB_APP_NAME
              value: anvilops
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-secret
            - name: PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: project-name
            - name: PROJECT_NS
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: project-ns
            - name: KUBECONFIG
              value: "/opt/creds/kubeconfig"
            - name: FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: field-encryption-key
            - name: DELETE_REPO_USER
              valueFrom:
                secretKeyRef:
                  name: registry-credentials
                  key: delete-user
            - name: BUILD_LOGGING_INGEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: logging-ingest-secret
                  key: secret
          volumeMounts:
            - mountPath: "/opt/creds"
              name: kube-auth
              readOnly: true
      volumes:
        - name: kube-auth
          secret:
            secretName: kube-auth
            items:
              - key: kubeconfig
                path: kubeconfig
