{{- if .Values.anvilops.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anvilops.serviceAccountName" . }}
  labels:
    {{- include "anvilops.labels" . | nindent 4 }}
  {{- with .Values.anvilops.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

{{- end }}

---
{{- if .Values.anvilops.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "anvilops.fullname" . }}-cluster-role
  labels:
    {{- include "anvilops.commonLabels" . | nindent 4 }}
rules:
# Monitoring a deployment in the dashboard:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", ]
- apiGroups: [""]
  resources: ["events", "pods/logs", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Builds:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "delete"]
# Creating/updating resources as a part of deploying a user's app:
- apiGroups: [""]
  resources: ["statefulsets", "namespaces", "secrets"]
  verbs: ["get", "list", "update", "watch", "patch", "create", "delete"]
- apiGroups: ["logging.banzaicloud.io"]
  resources: ["outputs", "flows"]
  verbs: ["get", "list", "update", "watch", "patch", "create", "delete"]
{{- end }}
---

{{- if .Values.anvilops.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "anvilops.fullname" . }}-crb
  labels:
    {{- include "anvilops.commonLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "anvilops.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "anvilops.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
