apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvilops.fullname" . }}
  labels:
    {{- include "anvilops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.anvilops.service.type }}
  ports:
    - port: {{ .Values.anvilops.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "anvilops.selectorLabels" . | nindent 4 }}
