apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: anvilops-allow-apps
  labels:
    {{- include "anvilops.commonLabels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{- include "anvilops.appLabels" . | nindent 10 }}
  podSelector: {}
  policyTypes:
    - Ingress