apiVersion: v1
kind: ConfigMap
metadata:
  name: anvilops-cluster-config
  labels:
    {{ include "anvilops.commonLabels" . | nindent 4 }}
data:
  cluster.json: |
    {{- toJson .Values.anvilops.cluster | nindent 4 }}