apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  selector:
    matchLabels:
      app: anvilops
  template:
    metadata:
      labels:
        app: anvilops
    spec:
      containers:
        - name: anvilops
          image: registry.anvil.rcac.purdue.edu/anvilops/anvilops:main-34-8a6c2b542921feabed6e74dadf00540f55686c9a # {"$imagepolicy": "anvilops-dev:anvilops-imagepolicy"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 512Gi
              cpu: 512m
            limits:
              memory: 1Gi
              cpu: 1024m
          env:
            - name: POSTGRES_USER
              value: anvilops
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: POSTGRES_DB
              value: anvilops
            - name: POSTGRES_HOSTNAME
              value: anvilops-postgres
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: webhook-secret
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: private-key
            - name: GITHUB_BASE_URL
              value: https://github.rcac.purdue.edu
            - name: GITHUB_APP_NAME
              value: anvilops-development
