apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  selector:
    matchLabels:
      app: anvilops
  template:
    metadata:
      labels:
        app: anvilops
    spec:
      containers:
        - name: anvilops
          image: registry.anvil.rcac.purdue.edu/anvilops/anvilops:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
