apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  selector:
    matchLabels:
      app: anvilops
  template:
    metadata:
      labels:
        app: anvilops
    spec:
      containers:
        - name: anvilops
          image: registry.anvil.rcac.purdue.edu/anvilops/anvilops:main-24-fec7e1b6fbbe875137f6ef3f76b6769026cf9bfc # {"$imagepolicy": "anvilops-dev:anvilops-imagepolicy"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
