apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anvilops-ingress
  namespace: anvilops-dev
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - anvilops.rcac.purdue.edu
  rules:
  - host: anvilops.rcac.purdue.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anvilops-service
            port:
              number: 80
