apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anvilops-dev
resources:
  - anvilops-deployment.yaml
  - harbor-receiver.yaml
  - service.yaml
  - ingress.yaml
  - imageupdate.yaml
  - proxy/
