apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- anvilops-deployment.yaml
- gitrepository.yaml
- harbor-receiver.yaml
- load-balancer.yaml
- notification-receiver.yaml
- system.yaml
