apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvilops.fullname" . }}-app-proxy-svc
  labels:
    {{ include "anvilops.commonLabels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "anvilops.fullname" . }}-app-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.appProxy.service.port }}
      targetPort: 80
  type: {{ .Values.appProxy.service.type }}
