apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anvilops.fullname" . }}-app-proxy
  labels:
    app: {{ include "anvilops.fullname" . }}-app-proxy
    {{ include "anvilops.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "anvilops.fullname" . }}-app-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "anvilops.fullname" . }}-app-proxy
    spec:
      containers:
        - name: app-proxy
          image: {{ .Values.appProxy.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: proxy-config
          configMap:
            name: proxyconf
