# from https://blog.meain.io/2020/dynamic-reverse-proxy-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxyconf
  labels:
    {{ include "anvilops.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log /dev/stderr warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /dev/stdout  main;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen 80;

        server_name ~^(?<subdomain>.*?)\.;
        {{- with .Values.anvilops.dnsResolver }}
        resolver {{ . }} valid=5s;
        {{- end }}

        location /healthz {
          return 200;
        }

        location = /unavailable.html {
          internal;
          alias /usr/share/nginx/html/unavailable.html;
        }

        location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://anvilops-$subdomain.anvilops-$subdomain.svc.cluster.local;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_intercept_errors on;
          error_page 502 =200 /unavailable.html;
        }
      }
    }
