apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-ingress
  namespace: anvilops-dev
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.anvilops.rcac.purdue.edu"
      secretName: tls-cert
  rules:
    - host: "*.anvilops.rcac.purdue.edu"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-proxy-svc
                port:
                  number: 80
