apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-proxy
  namespace: anvilops-dev
  labels:
    app: app-proxy
    app.kubernetes.io/name: proxy-sandbox
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/managed-by: fluxcd
spec:
  selector:
    matchLabels:
      app: app-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: app-proxy
    spec:
      containers:
        - name: app-proxy
          image: registry.anvil.rcac.purdue.edu/anvilops/sandbox-proxy:main-7-8f66831a0084135a35a2a24ade4bc1172a3262a8
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: proxy-config
          configMap:
            name: proxyconf
