{{ if .Values.buildkitd.install -}}
# Modified from https://github.com/moby/buildkit/blob/master/examples/kubernetes/deployment%2Bservice.rootless.yaml under the Apache-2.0 license
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "anvilops.buildkitd.labels" . | nindent 4 }}
  name: {{ include "anvilops.fullname" . }}-buildkitd
spec:
  replicas: {{ .Values.buildkitd.replicaCount }}
  selector:
    matchLabels:
      {{- include "anvilops.buildkitd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "anvilops.buildkitd.labels" . | nindent 8 }}
    spec:
      {{ if .Values.buildkitd.enableUserNamespaces -}}
      hostUsers: false
      {{- end }}
      containers:
        - name: buildkitd
          image: moby/buildkit:master
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
            - --debug
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 8000m
              memory: 32Gi
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
      volumes:
        # buildkit-daemon-certs must contain ca.pem, cert.pem, and key.pem
        - name: certs
          secret:
            secretName: buildkit-daemon-certs
        - name: buildkitd
          emptyDir: {}

{{- end }}