{{ if .Values.buildkitd.install -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "anvilops.buildkitd.labels" . | nindent 4 }}
  name: {{ include "anvilops.fullname" . }}-buildkitd
spec:
  ports:
    - port: 1234
      protocol: TCP
  selector:
    {{- include "anvilops.buildkitd.selectorLabels" . | nindent 4 }}
{{- end }}