apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spilo.fullname" . }}
  labels:
    {{- include "spilo.labels" . | nindent 4 }}
type: Opaque
data:
  superuser-password: {{ .Values.passwords.superuser | b64enc | quote }}
  replication-password: {{ .Values.passwords.replication | b64enc | quote }}
  admin-password: {{ .Values.passwords.admin | b64enc | quote }}
