apiVersion: v1
kind: Service
metadata:
  name: {{ include "spilo.fullname" . }}-repl
  labels:
    {{- include "spilo.labels" . | nindent 4 }}
    role: replica
spec:
  type: ClusterIP
  selector:
    {{- include "spilo.labels" . | nindent 4 }}
    role: replica
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432