apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - helm-chart.yaml
  - harbor-receiver.yaml
  - imageupdate.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: anvilops
      spec:
        chartRef:
          namespace: anvilops-dev
namespace: anvilops-dev
commonLabels:
  environment: dev
