passwords:
  superuser: "change-me"
  replication: "change-me"
  admin: "change-me"

storage:
  className: "standard"
  size: "5Gi"

image:
  repository: registry.opensource.zalan.do/acid/spilo-11
  tag: "1.5-p5"

replicas: 3
