apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvilops.fullname" . }}-postgres
  labels:
    {{- include "anvilops.postgres.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    {{- include "anvilops.postgres.selectorLabels" . | nindent 4 }}