name: Build and Publish File Browser Docker Image
on:
  push:
    branches: [main]
    paths:
      - "filebrowser/**"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push file browser image to registry
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout files
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            filebrowser/

      - name: Log in to container registry
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' registry.anvil.rcac.purdue.edu

      - name: Build and push AnvilOps Docker image
        run: docker build --push -t registry.anvil.rcac.purdue.edu/anvilops/file-browser:${{ github.ref_name }}-${{ github.run_number }}-${{ github.sha }}${{ github.event_name == 'push' && ' -t registry.anvil.rcac.purdue.edu/anvilops/file-browser:latest' || '' }} --cache-from=type=registry,ref=registry.anvil.rcac.purdue.edu/anvilops/file-browser:latest --cache-to=type=inline ./filebrowser

      - name: Log out of container registry
        if: always()
        run: docker logout registry.anvil.rcac.purdue.edu
