name: Lint
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: |
            frontend/package.json
            backend/package.json
            filebrowser/package.json

      - name: Install NPM packages
        run: |
          cd frontend
          npm ci
          cd ../backend
          npm ci
          cd ../filebrowser
          npm ci

      - name: Install Tools
        uses: jdx/mise-action@v3
        with:
          version: 2026.1.4
          install: true
          mise_toml: |
            [tools]
            hadolint = "2.14.0"
            golangci-lint = "2.8.0"

      - name: Lint
        run: ./.github/workflows/lint/lint.sh
