on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version number (production only)"
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ inputs.environment }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Log in to image registry (Production)
        if: ${{ inputs.environment == 'production' }}
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' registry.anvil.rcac.purdue.edu

      - name: Log in to image registry (Staging)
        if: ${{ inputs.environment == 'staging' }}
        run: docker login -u '${{ secrets.DOCKER_USERNAME_STAGING }}' -p '${{ secrets.DOCKER_PASSWORD_STAGING }}' registry.anvil.rcac.purdue.edu

      - name: Set up Git (Production)
        if: ${{ inputs.environment == 'production' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # This step is necessary because our script uses the destination OCI registry as a layer cache, which isn't supported by Docker out of the box.
        # See https://docs.docker.com/build/cache/backends/registry/ and https://docs.docker.com/build/builders/drivers/ for more info.
      - name: Set up buildx builder
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Release
        run: ./.github/workflows/scripts/release-${{ inputs.environment }}.sh "${{ inputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log out of container registry
        if: always()
        run: docker logout registry.anvil.rcac.purdue.edu
